package form;

import com.mysql.cj.xdevapi.Result;
import konfigurasi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author icank
 */
public class FormMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form FormMahasiswa
     */
    private DefaultTableModel DftTblModel_mhs;
    private String SQL;
    private ResultSet RsMaba=null;

    /**
     * method for showing data table
     */
    public void TampilkanData() {
        DftTblModel_mhs = new DefaultTableModel();
        DftTblModel_mhs.addColumn("Nim");
        DftTblModel_mhs.addColumn("Nama");
        DftTblModel_mhs.addColumn("Kelas");
        DftTblModel_mhs.addColumn("Jurusan");
        jTable_mhs.setModel(DftTblModel_mhs);
        Connection conn = Koneksi.getConnection();
        // try connecting to MySql
        try {
          java.sql.Statement stmt = conn.createStatement();
          SQL = "select * from maba";
          java.sql.ResultSet res = stmt.executeQuery(SQL);
          // looping
          while (res.next()) {
              DftTblModel_mhs.addRow(new Object[] {
                res.getString("nim_mhs"),   
                res.getString("nama_mhs"),
                res.getString("kelas_mhs"),
                res.getString("jurusan_mhs")
            });
          }
          
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void cariData(String key) {
        try {
           Object[] judul_kolom = {"Nim Mahasiswa", "Nama Mahasiswa", "Kelas", "Jurusan"};
           DftTblModel_mhs = new DefaultTableModel(null, judul_kolom);
           jTable_mhs.setModel(DftTblModel_mhs);
           
           Connection conn = Koneksi.getConnection();
           Statement stmt = conn.createStatement();
           DftTblModel_mhs.getDataVector().removeAllElements();
           
           RsMaba=stmt.executeQuery("SELECT * from maba WHERE nim_mhs LIKE '%"+key+"%' OR nama_mhs LIKE '%"+key+"%' OR jurusan_mhs LIKE '%"+key+"%' OR kelas_mhs LIKE '%"+key+"%' ");
           while (RsMaba.next()) {
                Object[] data = {
                RsMaba.getString("nim_mhs"),   
                RsMaba.getString("nama_mhs"),
                RsMaba.getString("kelas_mhs"),
                RsMaba.getString("jurusan_mhs")
            };
            DftTblModel_mhs.addRow(data);
           }
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }
    
    // constructor
    public FormMahasiswa() {
        initComponents();
        this.TampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_nim_mhs = new javax.swing.JTextField();
        jTextField_nama_mhs = new javax.swing.JTextField();
        jTextField_kelas_mhs = new javax.swing.JTextField();
        jTextField_jurusan_mhs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_baru = new javax.swing.JButton();
        jButton_simpan = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        jButton_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_mhs = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton_keluar = new javax.swing.JButton();
        txt_nilai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD");
        setBackground(new java.awt.Color(42, 42, 42));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(27, 27, 27));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_nim_mhs.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField_nim_mhs.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(jTextField_nim_mhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 80, 171, -1));

        jTextField_nama_mhs.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField_nama_mhs.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(jTextField_nama_mhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 122, 279, -1));

        jTextField_kelas_mhs.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField_kelas_mhs.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(jTextField_kelas_mhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 168, 168, -1));

        jTextField_jurusan_mhs.setBackground(java.awt.SystemColor.controlDkShadow);
        jTextField_jurusan_mhs.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(jTextField_jurusan_mhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 214, 279, -1));

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Nim");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 88, -1, -1));

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 128, -1, -1));

        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Kelas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 174, -1, -1));

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 220, -1, -1));

        jButton_baru.setBackground(new java.awt.Color(1, 135, 135));
        jButton_baru.setForeground(new java.awt.Color(254, 254, 254));
        jButton_baru.setText("Baru");
        jButton_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_baruActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 70, -1));

        jButton_simpan.setBackground(new java.awt.Color(1, 135, 135));
        jButton_simpan.setForeground(new java.awt.Color(254, 254, 254));
        jButton_simpan.setText("Simpan");
        jButton_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 80, -1));

        jButton_edit.setBackground(new java.awt.Color(1, 135, 135));
        jButton_edit.setForeground(new java.awt.Color(254, 254, 254));
        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 70, -1));

        jButton_hapus.setBackground(new java.awt.Color(1, 135, 135));
        jButton_hapus.setForeground(new java.awt.Color(254, 254, 254));
        jButton_hapus.setText("Hapus");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 70, -1));

        jTable_mhs.setBackground(java.awt.SystemColor.desktop);
        jTable_mhs.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        jTable_mhs.setForeground(new java.awt.Color(254, 254, 254));
        jTable_mhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_mhs.setGridColor(new java.awt.Color(254, 254, 254));
        jTable_mhs.setSelectionForeground(new java.awt.Color(1, 1, 1));
        jTable_mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_mhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_mhs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 750, 230));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("PENDATAAN MAHASISWA BARU");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jButton_keluar.setBackground(new java.awt.Color(1, 135, 135));
        jButton_keluar.setForeground(new java.awt.Color(254, 254, 254));
        jButton_keluar.setText("Keluar");
        jButton_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_keluarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 70, -1));

        txt_nilai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nilaiKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 150, 30));

        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Cari");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        btn_reset.setBackground(new java.awt.Color(33, 33, 33));
        btn_reset.setForeground(new java.awt.Color(254, 254, 254));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // method untuk menyimpan data
    private void jButton_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_simpanActionPerformed
        // TODO add your handling code here:
        try {   
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO maba(nim_mhs, nama_mhs, kelas_mhs, jurusan_mhs) values(?,?,?,?)");
            stmt.setString(1, jTextField_nim_mhs.getText());
            stmt.setString(2, jTextField_nama_mhs.getText());
            stmt.setString(3, jTextField_kelas_mhs.getText());
            stmt.setString(4, jTextField_jurusan_mhs.getText());
            stmt.executeUpdate();
            TampilkanData();
        } catch (SQLException e) {  
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_simpanActionPerformed
    
    // method untuk mereset data pada text field
    private void jButton_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_baruActionPerformed
        // TODO add your handling code here:
        //jTextField_nim_mhs.setEditable(true);
        jTextField_nim_mhs.setText(null);
        jTextField_nama_mhs.setText(null);
        jTextField_kelas_mhs.setText(null);
        jTextField_jurusan_mhs.setText(null);
    }//GEN-LAST:event_jButton_baruActionPerformed
    
    // method untuk keluar dari aplikasi
    private void jButton_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_keluarActionPerformed
    
    // method untuk menampilkan data pada text field pada saat mengclick didalam tabel
    private void jTable_mhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_mhsMouseClicked
        // TODO add your handling code here:
        int baris = jTable_mhs.getSelectedRow();
        jTextField_nim_mhs.setText(DftTblModel_mhs.getValueAt(baris, 0).toString());
        jTextField_nama_mhs.setText(DftTblModel_mhs.getValueAt(baris, 1).toString());
        jTextField_kelas_mhs.setText(DftTblModel_mhs.getValueAt(baris, 2).toString());
        jTextField_jurusan_mhs.setText(DftTblModel_mhs.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_jTable_mhsMouseClicked
    
    // method untuk mengedit data
    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("UPDATE maba set nama_mhs=?, kelas_mhs=?, jurusan_mhs=? WHERE nim_mhs=?");
            stmt.setString(1, jTextField_nama_mhs.getText());
            stmt.setString(2, jTextField_kelas_mhs.getText());
            stmt.setString(3, jTextField_jurusan_mhs.getText());
            stmt.setString(4, jTextField_nim_mhs.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di ubah !", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilkanData();        // menampilkan data
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_editActionPerformed
    
    // method untuk menghapus data 
    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
        // TODO add your handling code here:
        Connection conn = Koneksi.getConnection();
            int confirm = JOptionPane.showConfirmDialog(null, "Anjirr seriusan lu mau di apus ?", "Konfirmasi", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirm == 0) { 
                try {   
                    java.sql.PreparedStatement stmt = conn.prepareStatement("DELETE from maba WHERE nim_mhs = '" + jTextField_nim_mhs.getText() + "'");
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data dah berhasil dihapus euyy :P", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                    TampilkanData();
                    jTextField_nim_mhs.setText("");
                    jTextField_nama_mhs.setText("");
                    jTextField_kelas_mhs.setText("");
                    jTextField_jurusan_mhs.setText("");
                    jTextField_nim_mhs.requestFocus();   
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Data gagal di hapus :(" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_jButton_hapusActionPerformed
    
    /* method untuk melakukan pencarian data (searching)    */
    
    // method untuk tombol reset
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        this.TampilkanData();
    }//GEN-LAST:event_btn_resetActionPerformed
    
    // method untuk searching
    private void txt_nilaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nilaiKeyReleased
        // TODO add your handling code here:
        String key = txt_nilai.getText();
        System.out.println(key);
        
        if (key != "") {
            cariData(key);
        }else{
            TampilkanData();
        }           
    }//GEN-LAST:event_txt_nilaiKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton jButton_baru;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JButton jButton_keluar;
    private javax.swing.JButton jButton_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_mhs;
    private javax.swing.JTextField jTextField_jurusan_mhs;
    private javax.swing.JTextField jTextField_kelas_mhs;
    private javax.swing.JTextField jTextField_nama_mhs;
    private javax.swing.JTextField jTextField_nim_mhs;
    private javax.swing.JTextField txt_nilai;
    // End of variables declaration//GEN-END:variables
}
